version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: economic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_project.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/economic_db
      - DEBUG=False
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./vite.config.ts:/app/vite.config.ts
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_ECONOMIC_API_ENDPOINT=/api/economic
    depends_on:
      - backend

volumes:
  postgres_data:
